# Use the official Liquibase image as the base image
FROM liquibase/liquibase:latest

# Set the INSTALL_MYSQL environment variable to true
ENV INSTALL_MYSQL=true

# Copy the custom entrypoint script into the container
COPY liquibase-mysql-driver.sh /liquibase-mysql-driver.sh

# Make the entrypoint script executable
RUN chmod +x /liquibase-mysql-driver.sh

# Set the custom entrypoint script
ENTRYPOINT ["/liquibase-mysql-driver.sh"]
